- name: print playlevel variables
  hosts: web
  vars:
    app_name: "nginx"
    port: 80
    ENV: "development"
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "{{ app_name }} {{ port }} {{ ENV }}"
    
    - name: Get public IP address
      community.general.ipify_facts:
      register: public_ip_info

    # - name: Print Private and Public IP
    #   ansible.builtin.debug:
    #     msg:
    #       - "Private IP: {{ ansible_default_ipv4.address }}"
    #       - "Public IP: {{ ansible_facts.ipify_public_ip }}"

    - name: Store public and private IPs in a single fact variable
      ansible.builtin.set_fact:
        remote_ips:
          private: "{{ ansible_default_ipv4.address }}"
          public: "{{ ansible_facts.ipify_public_ip }}"

    - name: Verify the stored variable from ansible_facts
      ansible.builtin.debug:
        msg:
          - "Full Variable: {{ ansible_facts.remote_ips }}"
          - "Just Private: {{ ansible_facts.remote_ips.private }}"
          - "Just Public: {{ ansible_facts.remote_ips.public }}"