- name: print playlevel variables
  hosts: web
  vars:
    app_name: "nginx"
    port: 80
    ENV: "development"
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "{{ app_name }} {{ port }} {{ ENV }}"
    
    - name: Get public IP address
      community.general.ipify_facts:
      register: public_ip_info

    - name: inspect ipify_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Store public and private IPs
      ansible.builtin.set_fact:
        remote_ips:
          private: "{{ ansible_default_ipv4.address }}"
          public: "{{ ansible_facts.ipify_public_ip }}"
    - name: Verify stored variable
      ansible.builtin.debug:
        msg:
          - "Full Variable: {{ remote_ips }}"
          - "Just Private: {{ remote_ips.private }}"
          - "Just Public: {{ remote_ips.public }}"